### PR TITLE
Update quantize command to properly suffix input file

### PR DESCRIPTION
**Pull request by rizenfrmtheashes**
I believe the original code keeps on quantizing the first file, not all files for models that have more than one input quantize file. This update should fix that.

### CODE REVIEW

**Comment by fermigas** [comment]
This is one of the reasons that only the 7B model runs. 

Another reason may be line 124 in dalai/index.js: 

model: `./models/${req.model || "7B"}/ggml-model-q4_0.bin`

It doesn't seem to be aware that the larger models have more than one q4 file.  

Also, in the form  (index.ejs, 57-60), pressing autocomplete results in this request:  

socket.emit('request', {
      prompt: input.textContent,
      n_predict: 256
    })
    
    which does not specify which model, so defaults to 7B.

**Comment by rizenfrmtheashes** [comment]
> Another reason may be line 124 in dalai/index.js:
> 
> model: `./models/${req.model || "7B"}/ggml-model-q4_0.bin`
> 
> It doesn't seem to be aware that the larger models have more than one q4 file.

Actually this is fine. the underlying llama.cpp package only requires referencing the first model weights file, even if you have multiple, so this _should_ be okay.  This is based on my manual testing of the underlying package used, not an e2e test.

**Comment by marcuswestin** [comment]
@rizenfrmtheashes I implemented that web ui in #16 - would love a code review if you're up for it.

But I did *not* verify that the requested model gets propagated all the way down! I simply assumed that that worked.

**Comment by fermigas** [comment]
@marcuswestin a lot of great usability fixes/adds in those commits!  LGTM

**Pull request merged**
